### PR TITLE
[WIP] fix issue #6 : Create CommentsOverlay component

### PR DESCRIPTION
**Pull request by AlphaFlagship**
I had just understood the fundamentals, in just a couple of days I 'll complete it. This commit is nearly similar to that of devanshu

### CODE REVIEW

**Comment by AlphaFlagship** [comment]
Sample Screenshots 
Screenshot_2021-07-22-17-02-23-471_host exp exponent
Screenshot_2021-07-22-16-53-33-520_host exp exponent

**Comment by kartikcode** [comment]
The UI looks decent. For the back button, I think it would be better if you use the react native element icons. You can read about the same [here](https://reactnativeelements.com/docs/icon/). Preferably use `font-awesome-5` package. Same goes for the upvote and the downvote buttons as well. Using icons would also fix the weird margins of these buttons.

**Comment by AlphaFlagship** [comment]
Corrected icons,
 any other improvement?

Screenshot_2021-07-24-13-56-25-924_host exp exponent

**Comment by AlphaFlagship** [comment]
i had used font awesome's free solid icons, if pro icons can also be used please let me know.

**Comment by kartikcode** [comment]
LGTM, the margin still looks a bit off. Try and fix it. (the space between the upvote icon and stats)

**Comment by AlphaFlagship** [comment]
Actually I have made  margins to decrease with nested replies. You want the margins to be same for all the comments?

**Comment by AlphaFlagship** [comment]
image

**Comment by kartikcode** [comment]
Merged.

**Pull request merged**
